# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm run install:client
        
      - name: Build 
        run: npm run build:client
        env:
          VITE_API_SERVER_URL: https://rental-app-api-k4v6eblhva-uw.a.run.app
          VITE_MAP_API_KEY: ${{ secrets.MAP_API_KEY }}
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-artifact
          retention-days: 7
          path: client/dist