name: Preview Teardown 

on:
  pull_request:
    types: [ closed ]
    paths:
      - 'client/**'

jobs:
  teardown:
    name: Teardown preview on Surge
    runs-on: ubuntu-latest
    if: github.repository_owner == 'RentalReviews'
    env:
      SURGE_DOMAIN: ${{ format('https://{0}-{1}-pr{2}-preview.surge.sh', github.repository_owner, 
        github.event.repository.name, github.event.pull_request.number) }}
    permissions:
      pull-requests: write
      issues: write

    steps:
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Surge
      run: npm install --global surge

    - name: Teardown preview on Surge
      continue-on-error: true
      run: surge teardown ${{ env.SURGE_DOMAIN }}
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
