name: Server pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/server.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json

    - name: Install dependencies
      run: npm run install:server
    
    - name: Run Prettier
      run: npm run prettier:server

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json

    - name: Install dependencies
      run: npm run install:server
      
    - name: Build 
      run: npm run build:server

  migrate:
    name: Perform Migration
    runs-on: ubuntu-latest
    if: github.repository_owner == 'RentalReviews' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json

    - name: Check for changes to schema
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          prisma:
            - 'api/prisma/**'
    
    - name: Authenticate with GCP
      id: auth
      if: steps.changes.outputs.prisma == 'true'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.CLOUD_SQL_CREDENTIAL }}'

    - name: Install dependencies
      if: steps.changes.outputs.prisma == 'true'
      run: npm run install:server

    - name: Install Cloud SQL Proxy
      if: steps.changes.outputs.prisma == 'true'
      run: |
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.0.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        sudo mv cloud-sql-proxy /usr/local/bin/

    - name: Connect to Cloud SQL
      if: steps.changes.outputs.prisma == 'true'
      run: cloud-sql-proxy ${{ secrets.CLOUD_SQL_INSTANCE }} & 

    - name: Prisma migrate deploy
      if: steps.changes.outputs.prisma == 'true'
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: cd api && npx prisma migrate deploy

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: github.repository_owner == 'RentalReviews' && github.event_name == 'push'
    needs: [build]
    env:
      GCP_REGION: us-west1
      GCP_REPOSITORY: rental-app-api
      IMAGE_TAG: ${{ format('api:{0}', github.sha) }}
      IMAGE_URL:  ${{ format('{0}-docker.pkg.dev/{1}/{2}/{3}', env.GCP_REGION, 
        secrets.PROJECT_ID, env.GCP_REPOSITORY, env.IMAGE_TAG) }}

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate with GCP
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.DEPLOY_CREDENTIAL }}'

    - name: Configure Docker 
      run: |
        gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ env.IMAGE_TAG }} api/
        docker tag ${{ env.IMAGE_TAG }} ${{ env.IMAGE_URL }}

    - name: Push image to GCP Artifact Registry
      run: |
        docker push ${{ env.IMAGE_URL }}

    - name: Push to Cloud Run
      id: cloud-run-deploy
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'rental-app-api'
        region: ${{ env.GCP_REGION }}
        project_id: ${{ secrets.PROJECT_ID }}
        image: ${{ env.IMAGE_URL }}

    - name: Output
      run: 'curl "${{ steps.cloud-run-deploy.outputs.url }}"'
